"""Initial migration

Revision ID: 6751ba10e0b7
Revises: 5d4ce4afe005
Create Date: 2025-02-16 22:51:07.824942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6751ba10e0b7'
down_revision: Union[str, None] = '5d4ce4afe005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
